# Generated by Django 4.1.2 on 2022-11-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='1', help_text='format: required, max-100', max_length=100, verbose_name='category_name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='def', help_text='format: required, letters, numbers, underscores, or hypthens', max_length=150, verbose_name='category safe URL'),
            preserve_default=False,
        ),
    ]
